
OPD(tok_plus, "+")
OPD(tok_minus, "-")
OPD(tok_inc, "++")
OPD(tok_pluseq, "+=")
OPD(tok_dec, "--")
OPD(tok_minuseq, "-=")

OPD(tok_gt, ">")
OPD(tok_gteq, ">=")
OPD(tok_rshift, ">>")

OPD(tok_lt, "<")
OPD(tok_lteq, "<=")
OPD(tok_lshift, "<<")

OPD(tok_btand, "&")
OPD(tok_and, "&&")

OPD(tok_btor, "|")
OPD(tok_or, "||")

OPD(tok_assign, "=")
OPD(tok_equals, "==")

OPD(tok_mul, "*")
OPD(tok_div, "/")
OPD(tok_not, "!")
OPD(tok_oparen, "(")
OPD(tok_cparen, ")")
OPD(tok_obrace, "{")
OPD(tok_cbrace, "}")
OPD(tok_semic, ";")
OPD(tok_colon, ":")